/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/administradores/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/laboratorios/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/laboratorios/inventario`; params?: Router.UnknownInputParams; } | { pathname: `/tecnicos/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/tecnicos/entrada`; params?: Router.UnknownInputParams; } | { pathname: `/tecnicos/gestion_inventarios`; params?: Router.UnknownInputParams; } | { pathname: `/tecnicos/salida`; params?: Router.UnknownInputParams; } | { pathname: `/usuarios/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/administradores/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/laboratorios/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/laboratorios/inventario`; params?: Router.UnknownOutputParams; } | { pathname: `/tecnicos/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/tecnicos/entrada`; params?: Router.UnknownOutputParams; } | { pathname: `/tecnicos/gestion_inventarios`; params?: Router.UnknownOutputParams; } | { pathname: `/tecnicos/salida`; params?: Router.UnknownOutputParams; } | { pathname: `/usuarios/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(login)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/administradores/dashboard${`?${string}` | `#${string}` | ''}` | `/laboratorios/dashboard${`?${string}` | `#${string}` | ''}` | `/laboratorios/inventario${`?${string}` | `#${string}` | ''}` | `/tecnicos/dashboard${`?${string}` | `#${string}` | ''}` | `/tecnicos/entrada${`?${string}` | `#${string}` | ''}` | `/tecnicos/gestion_inventarios${`?${string}` | `#${string}` | ''}` | `/tecnicos/salida${`?${string}` | `#${string}` | ''}` | `/usuarios/dashboard${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/administradores/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/laboratorios/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/laboratorios/inventario`; params?: Router.UnknownInputParams; } | { pathname: `/tecnicos/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/tecnicos/entrada`; params?: Router.UnknownInputParams; } | { pathname: `/tecnicos/gestion_inventarios`; params?: Router.UnknownInputParams; } | { pathname: `/tecnicos/salida`; params?: Router.UnknownInputParams; } | { pathname: `/usuarios/dashboard`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | 
                  `/tecnicos/mantenimiento${`?${string}` | `#${string}` | ''}` | `/tecnicos/registro_mantenimiento${`?${string}` | `#${string}` | ''}` | `/administradores/gestion_usuarios${`?${string}` | `#${string}` | ''}` | `/administradores/configuracion_parametros${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
